### ISSUE TITLE
nodejs8.10 is no longer a supported runtime

### ISSUE THREAD

**Issue by maishsk** [aws-samples/amazon-kinesis-analytics-beam-taxi-consumer#1]
Should be changed to nodejs10.x

**Comment by sthm** [comment]
Thanks a lot for reporting this. The CloudFormation templates are actually generated from a CDK template, which currently does not support inline functions for node10.x: https://github.com/aws/aws-cdk/issues/4642.

I've merged your pull request as a short term fix, but will leave the issue open until I can update the CDK template.
