### ISSUE TITLE
Apache Beam Runner Compatibility Matrix / Flink on Kinesis Compatibility

### ISSUE THREAD

**Issue by leofischer** [aws-samples/amazon-kinesis-analytics-beam-taxi-consumer#3]
Hi,

Would you be able provide a bit more information about the runner being used, does it run directly against Kinesis or can we now directly target [the new Kinesis Flink runtime](https://docs.aws.amazon.com/kinesisanalytics/latest/java/how-it-works.html)?

If it does directly target Kinesis, would you have any information on the compatibility or limitations of the Apache Beam running on Kinesis or the limitations of running Beam?  This example seems comprehensive, though I haven't found any additional information for the runner other than [some source  in beam repo](https://github.com/apache/beam/tree/master/sdks/java/io/kinesis/src/main/java/org/apache/beam/sdk/io/kinesis) and Kinesis doesn't appear to be listed as a runner in the [beam compatibility matrix](https://beam.apache.org/documentation/runners/capability-matrix/).

If we can now directly target Flink, are there any caveats or implementations details that we should know about and how would we change this example?

**Comment by sthm** [comment]
The sources are using the Flink runner to execute a Beam pipeline with Kinesis Data Analytics for Java Applications, which basically provides a managed Apache Flink runtime. So, the runtime supports everything that is supported by Flink in the capability matrix.

As it is using a managed service, some restrictions apply. Most importantly in this context, you cannot customize the Flink runtime as you don't have any access to it. Therefore, you can only use the Beam Java API. But other than that, it should be quite similar to running Beam on yourself managed Flink cluster.

**Comment by leofischer** [comment]
Ok, we can work with that, thanks @sthm!
